apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: shipment.events
  namespace: smartship
  labels:
    strimzi.io/cluster: events-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 
    segment.bytes: 1073741824 
