apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smartship

resources:
  - namespace.yaml
  - kafka-cluster.yaml
  - kafka-topic.yaml
  - apicurio-registry.yaml
  - postgresql.yaml

configMapGenerator:
  - name: postgresql-init
    files:
      - init.sql
    options:
      disableNameSuffixHash: true

