apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generators
  namespace: smartship
spec:
  template:
    spec:
      containers:
      - name: data-generators
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-api
  namespace: smartship
spec:
  template:
    spec:
      containers:
      - name: query-api
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: streams-processor
  namespace: smartship
spec:
  template:
    spec:
      containers:
      - name: streams-processor
        imagePullPolicy: IfNotPresent
